# If want to input None, use !!null
sock_data: 5001

batch_size: 256 # def: 256

# Directories
train_folder: imagenet/ilsvrc2012/train_hkl_b256_b256_bchw/
val_folder: imagenet/ilsvrc2012/val_hkl_b256_b256_bchw/
