# If want to input None, use !!null
sock_data: 5001

batch_size: 256 # def: 256

# Directories
train_folder: /data/tmp/ciyong/Image100/train_hkl_b256_b256_bchw/
val_folder: /data/tmp/ciyong/Image100/val_hkl_b256_b256_bchw/
#train_folder: /data/tmp/ciyong/imagenet/parsed_data/train_hkl_b256_b256_bchw/
#val_folder: /data/tmp/ciyong/imagenet/parsed_data/val_hkl_b256_b256_bchw/
